(define (gao n)
 (do ((d (do ((i (- n 1) (- i 1))
              (d '() (cons i d)))
             ((< i 0) d))
         (append (cddr d) (list (car d)))))
     ((null? (cdr d)) (car d))))
(display (gao 987654321))
