/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package qlcoder;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Type implements TEnum {
  GET_ANSWER(1),
  GET_CREATEDTIME(2),
  GET_AUTHOR(3);

  private final int value;

  private Type(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Type findByValue(int value) { 
    switch (value) {
      case 1:
        return GET_ANSWER;
      case 2:
        return GET_CREATEDTIME;
      case 3:
        return GET_AUTHOR;
      default:
        return null;
    }
  }
}
