# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='tutorial',
  serialized_pb=_b('\n\ntask.proto\x12\x08tutorial\"\xed\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x02(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x02(\x05\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12%\n\x06\x61nswer\x18\x06 \x03(\x0b\x32\x15.tutorial.Task.Answer\x1a\x44\n\x06\x41nswer\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x05\x12,\n\x04type\x18\x02 \x01(\x0e\x32\x19.tutorial.Task.AnswerType:\x03INT\"-\n\nAnswerType\x12\n\n\x06STRING\x10\x00\x12\x07\n\x03INT\x10\x01\x12\n\n\x06\x44OUBLE\x10\x02\"\'\n\x07\x41\x64\x64Task\x12\x1c\n\x04task\x18\x01 \x03(\x0b\x32\x0e.tutorial.Task')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TASK_ANSWERTYPE = _descriptor.EnumDescriptor(
  name='AnswerType',
  full_name='tutorial.Task.AnswerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=217,
  serialized_end=262,
)
_sym_db.RegisterEnumDescriptor(_TASK_ANSWERTYPE)


_TASK_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='tutorial.Task.Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='tutorial.Task.Answer.data', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='tutorial.Task.Answer.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=215,
)

_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='tutorial.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tutorial.Task.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='tutorial.Task.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='tutorial.Task.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='tutorial.Task.score', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='author', full_name='tutorial.Task.author', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answer', full_name='tutorial.Task.answer', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TASK_ANSWER, ],
  enum_types=[
    _TASK_ANSWERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=262,
)


_ADDTASK = _descriptor.Descriptor(
  name='AddTask',
  full_name='tutorial.AddTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task', full_name='tutorial.AddTask.task', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=303,
)

_TASK_ANSWER.fields_by_name['type'].enum_type = _TASK_ANSWERTYPE
_TASK_ANSWER.containing_type = _TASK
_TASK.fields_by_name['answer'].message_type = _TASK_ANSWER
_TASK_ANSWERTYPE.containing_type = _TASK
_ADDTASK.fields_by_name['task'].message_type = _TASK
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['AddTask'] = _ADDTASK

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(

  Answer = _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), dict(
    DESCRIPTOR = _TASK_ANSWER,
    __module__ = 'task_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.Task.Answer)
    ))
  ,
  DESCRIPTOR = _TASK,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Task)
  ))
_sym_db.RegisterMessage(Task)
_sym_db.RegisterMessage(Task.Answer)

AddTask = _reflection.GeneratedProtocolMessageType('AddTask', (_message.Message,), dict(
  DESCRIPTOR = _ADDTASK,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.AddTask)
  ))
_sym_db.RegisterMessage(AddTask)


# @@protoc_insertion_point(module_scope)
